# pytest.ini or .pytest.ini
[pytest]
minversion = 6.0
addopts = --html=./reports/report.html --self-contained-html -v -s --tb=short --cov=src --cov-report=term-missing
testpaths =
    tests
pythonpath = .